# Generated by Django 4.2.4 on 2023-09-05 19:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("cover", models.URLField(blank=True)),
                ("video", models.URLField(blank=True)),
                ("title", models.TextField(max_length=150)),
                ("body", ckeditor.fields.RichTextField(max_length=8000)),
                ("post_type", models.CharField(max_length=50)),
                ("latest", models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.URLField(blank=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="blog.blogpost",
                    ),
                ),
            ],
        ),
    ]
