# Generated by Django 4.2.4 on 2023-09-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="cover",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="video",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="cover_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
