# Generated by Django 4.2.4 on 2023-09-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_blogpost_cover_remove_blogpost_video_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="cover_url",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="video_url",
            field=models.CharField(blank=True, null=True),
        ),
    ]
