# Generated by Django 4.2.4 on 2023-09-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blogpost_cover_url_alter_blogpost_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="cover_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
